version: '3.5'

volumes:
  dbdata:
    driver: local

services:
  frontend:
    container_name: ${PROJECT_NAME}_frontend
    build: ./
    volumes:
      - './backend:/usr/src/app'
      - '.env:/usr/src/.env'
    ports:
      - '${FRONTEND_PORT}:3000'
    command: >
      bash -c "cd Alfred/Core && npm install && npm run watch"

  backend:
    image: nginx:alpine
    container_name: ${PROJECT_NAME}_backend
    hostname: ${NGINX_HOST}
    volumes:
      - "./etc/ssl:/etc/ssl:delegated"
      - "./backend:/var/www/html:delegated"
      - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template:delegated"
      - "./etc/nginx/nginx.conf:/etc/nginx/nginx.conf.default:delegated"
    env_file:
      - ".env"
    ports:
      - "${BACKEND_PORT}:8000"
    environment:
      - NGINX_HOST=${NGINX_HOST}
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always
    links:
      - mysqldb:mysqldb
    depends_on:
      - php
      - mysqldb
      - redis

  php:
    image: studiosidekicks/php-with-composer
    container_name: ${PROJECT_NAME}_php
    restart: always
    volumes:
      - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini:delegated"
      - "./backend:/var/www/html:delegated"
    links:
      - mysqldb:mysqldb

  redis:
    image: redis
    container_name: ${PROJECT_NAME}_redis
    ports:
      - "${REDIS_PORT}:6379"

  mysqldb:
    image: mariadb:10.3
    container_name: ${MYSQL_HOST}
    restart: always
    volumes:
      - ./etc/mysql/my.cnf:/etc/my.cnf
      - "dbdata:/var/lib/mysql:delegated"
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"